version: "3.7"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: tictactoe
      POSTGRES_USER: tictactoe
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "tictactoe", "-U", "tictactoe" ]
      timeout: 45s
      interval: 5s
      retries: 10

  tictactoe:
    build: .
    image: lutostag/tictactoe
    environment:
      TICTACTOE_DB: "postgresql://tictactoe:postgres@postgres/tictactoe"
    ports:
      - ${BIND:-127.0.0.1:80}:80

volumes:
  pgdata:
